#ifndef __CONFIG_H__
#define __CONFIG_H__

#define DEBUG false

#define ONEWIRE_PIN 22
#define CELL_MONITORS_UART_TX_PIN 4
#define CELL_MONITORS_UART_RX_PIN 5

#define CELL_MONITORS_INTERVAL 5000
#define CONNECT_TIMEOUT 10000
#define REQUEST_TIMEOUT 2000

#define CHARGE_CUTOFF_TEMP 8 // ~46F

#define PROTECTION_CHG_PIN 14
#define PROTECTION_DSG_PIN 15
#define PROTECTION_OV_ENABLE 3550
#define PROTECTION_OV_DISABLE 3350
#define PROTECTION_UV_ENABLE 3000
#define PROTECTIOn_UV_DISABLE 3100

#endif
