#ifndef __CONFIG_H__
#define __CONFIG_H__

#define DEBUG false

#define ONEWIRE_PIN 22
#define CELL_MONITORS_UART_TX_PIN 4
#define CELL_MONITORS_UART_RX_PIN 5

#define CELL_MONITORS_INTERVAL 5000
#define CONNECT_TIMEOUT 10000
#define REQUEST_TIMEOUT 2000

#define CHARGE_CUTOFF_TEMP 8 // ~46F

#endif
